In [21]:
from functools import reduce
import numpy as np

texts = [['i', 'have', 'a', 'cat'],
         ['he', 'have', 'a', 'dog'],
         ['he', 'and', 'i', 'have', 'a', 'cat', 'and', 'a', 'dog']]

dictionary = list(enumerate(set(list(reduce(lambda x, y: x + y, texts)))))

def vectorize(text):
    vector = np.zeros(len(dictionary))
    for i, word in dictionary:
        num = 0
        for w in text:
            if w == word:
                num += 1
        if num:
            vector[i] = num
    return vector

for t in texts:
    print(vectorize(t))

[1. 1. 1. 0. 0. 0. 1.]
[0. 1. 1. 1. 0. 1. 0.]
[1. 2. 1. 1. 2. 1. 1.]


In [22]:
dictionary

[(0, 'i'),
 (1, 'a'),
 (2, 'have'),
 (3, 'dog'),
 (4, 'and'),
 (5, 'he'),
 (6, 'cat')]